export { default as drslider} from '../../public/client/assets/images/dr-slider.png';
export { default as banner1} from '../../public/client/assets/images/banner-1.png';
export { default as banner4} from '../../public/client/assets/images/banner-4.jpg';
export { default as browse1} from '../../public/client/assets/images/browse/browse-img1.jpg';
export { default as browse2} from '../../public/client/assets/images/browse/browse-img2.jpg';
export { default as browse3} from '../../public/client/assets/images/browse/browse-img3.jpg';
export { default as browse4} from '../../public/client/assets/images/browse/browse-img4.jpg';
export { default as browse5} from '../../public/client/assets/images/browse/browse-img5.jpg';
export { default as browse6} from '../../public/client/assets/images/browse/browse-img6.jpg';
export { default as browse7} from '../../public/client/assets/images/browse/browse-img7.jpg';
export { default as browse8} from '../../public/client/assets/images/browse/browse-img8.jpg';

export { default as Slider1} from '../../public/client/assets/images/slider/slider-1.jpg';
export { default as Slider2} from '../../public/client/assets/images/slider/slider-2.jpg';
export { default as Slider3} from '../../public/client/assets/images/slider/slider-3.jpg';
export { default as Doctor01} from '../../public/client/assets/images/doctors/doctor-img1.png';
export { default as Doctor07} from '../../public/client/assets/images/doctors/doctor-07.jpg';
export { default as ImgPharmacy1} from '../../public/client/assets/images/img-pharmacy1.jpg';
export { default as LabImage} from '../../public/client/assets/images/lab-image.jpg';
export { default as Slide1} from '../../public/client/assets/images/slide1.jpg';
export { default as Slide2} from '../../public/client/assets/images/slide2.jpg';
export { default as Docslide1} from '../../public/client/assets/images/doc-slide-1.png';
export { default as logo} from '../../public/client/assets/images/logo.png';
export { default as banner6} from '../../public/client/assets/images/banner-6.jpg';
export { default as banner_check} from '../../public/client/assets/images/banner-check.png';
export { default as shapes_10} from '../../public/client/assets/images/shapes/shape-10.png';
export { default as shapes_7} from '../../public/client/assets/images/shapes/shape-7.png';
export { default as shapes_6} from '../../public/client/assets/images/shapes/shape-6.png';
export { default as shapes_8} from '../../public/client/assets/images/shapes/shape-8.png';
export { default as logo_one} from '../../public/client/assets/images/logo-one.png';
export { default as banner_img} from '../../public/client/assets/images/banner-img.png';
export { default as appoinment_img} from '../../public/client/assets/images/appoinment-img.png';
export { default as phone_call} from '../../public/client/assets/images/phone-call.png';
export { default as icon6} from '../../public/client/assets/images/icons/icon6.svg';
export { default as icon7} from '../../public/client/assets/images/icons/icon7.svg';
export { default as icon8} from '../../public/client/assets/images/icons/icon8.svg';
export { default as icon9} from '../../public/client/assets/images/icons/icon9.svg';
export { default as icon10} from '../../public/client/assets/images/icons/icon10.svg';
export { default as icon11} from '../../public/client/assets/images/icons/icon11.svg';
export { default as icon2} from '../../public/client/assets/images/icons/icon2.svg';
export { default as icon3} from '../../public/client/assets/images/icons/icon3.svg';
export { default as icon4} from '../../public/client/assets/images/icons/icon4.svg';
export { default as icon1} from '../../public/client/assets/images/icons/icon1.svg';
export { default as patient_icon} from '../../public/client/assets/images/icons/patient-icon.png';

export { default as services_01} from '../../public/client/assets/images/services/services-01.jpg';
export { default as services_02} from '../../public/client/assets/images/services/services-02.jpg';
export { default as services_03} from '../../public/client/assets/images/services/services-03.jpg';
export { default as services_04} from '../../public/client/assets/images/services/services-04.jpg';
export { default as features_01} from '../../public/client/assets/images/services/features-01.svg';
export { default as features_02} from '../../public/client/assets/images/services/features-02.svg';
export { default as features_03} from '../../public/client/assets/images/services/features-03.svg';
export { default as features_04} from '../../public/client/assets/images/services/features-04.svg';
export { default as features_05} from '../../public/client/assets/images/services/features-05.svg';
export { default as features_06} from '../../public/client/assets/images/services/features-06.svg';
export { default as doctor_img} from '../../public/client/assets/images/doctors/doctor-img.jpg';
export { default as features_clinic1} from '../../public/client/assets/images/clinic/features-clinic-01.jpg';
export { default as features_clinic2} from '../../public/client/assets/images/clinic/features-clinic-02.jpg';
export { default as features_clinic3} from '../../public/client/assets/images/clinic/features-clinic-03.jpg';
export { default as features_clinic4} from '../../public/client/assets/images/clinic/features-clinic-04.jpg';
export { default as book_doctor_01} from '../../public/client/assets/images/doctors/book-doctor-01.jpg';
export { default as book_doctor_02} from '../../public/client/assets/images/doctors/book-doctor-02.jpg';
export { default as book_doctor_03} from '../../public/client/assets/images/doctors/book-doctor-03.jpg';
export { default as book_doctor_04} from '../../public/client/assets/images/doctors/book-doctor-04.jpg';
export { default as book_doctor_05} from '../../public/client/assets/images/doctors/book-doctor-05.jpg';
export { default as book_doctor_06} from '../../public/client/assets/images/doctors/book-doctor-06.jpg';
export { default as book_doctor_07} from '../../public/client/assets/images/doctors/book-doctor-07.jpg';
export { default as book_doctor_08} from '../../public/client/assets/images/doctors/book-doctor-08.jpg';
export { default as book_doctor_09} from '../../public/client/assets/images/doctors/book-doctor-09.jpg';
export { default as book_doctor_10} from '../../public/client/assets/images/doctors/book-doctor-10.jpg';
export { default as book_doctor_11} from '../../public/client/assets/images/doctors/book-doctor-11.jpg';
export { default as book_doctor_12} from '../../public/client/assets/images/doctors/book-doctor-12.jpg';
export { default as book_doctor_13} from '../../public/client/assets/images/doctors/book-doctor-13.jpg';
export { default as book_doctor_14} from '../../public/client/assets/images/doctors/book-doctor-14.jpg';
export { default as book_doctor_15} from '../../public/client/assets/images/doctors/book-doctor-15.jpg';
export { default as book_doctor_16} from '../../public/client/assets/images/doctors/book-doctor-16.jpg';

export { default as doctor_thumb_01} from '../../public/client/assets/images/doctors/doctor-thumb-01.jpg';
export { default as doctor_thumb_02} from '../../public/client/assets/images/doctors/doctor-thumb-02.jpg';
export { default as doctor_thumb_03} from '../../public/client/assets/images/doctors/doctor-thumb-03.jpg';
export { default as doctor_thumb_04} from '../../public/client/assets/images/doctors/doctor-thumb-04.jpg';
export { default as best_doctor_check} from '../../public/client/assets/images/best-doctor-check.svg';
export { default as doctor_check} from '../../public/client/assets/images/doctor-check.png';
export { default as news_img} from '../../public/client/assets/images/blog/news-img.png';
export { default as news_letter} from '../../public/client/assets/images/blog/news-letter-img.png';
export { default as blog_01} from '../../public/client/assets/images/blog/blog-01.jpg';
export { default as blog_02} from '../../public/client/assets/images/blog/blog-02.jpg';
export { default as blog_04} from '../../public/client/assets/images/blog/blog-04.jpg';
export { default as blog_11} from '../../public/client/assets/images/blog/blog-11.jpg';
export { default as blog_12} from '../../public/client/assets/images/blog/blog-12.jpg';
export { default as blog_13} from '../../public/client/assets/images/blog/blog-13.jpg';
export { default as blog_wrap_03} from '../../public/client/assets/images/blog/blog-wrap-03.jpg';
export {default as blog_wrap_02} from '../../public/client/assets/images/blog/blog-wrap-02.jpg';

export { default as footer_logo} from '../../public/client/assets/images/footer-logo.png';
export { default as patient1} from '../../public/client/assets/images/doctors/patient-img1.png';
export { default as clinic_big_img} from '../../public/client/assets/images/clinic/clinic-big-img.png';
export { default as features_clinic_01} from '../../public/client/assets/images/clinic/features-clinic-01.jpg';
export { default as features_clinic_02} from '../../public/client/assets/images/clinic/features-clinic-02.jpg';
export { default as features_clinic_03} from '../../public/client/assets/images/clinic/features-clinic-03.jpg';
export { default as features_clinic_04} from '../../public/client/assets/images/clinic/features-clinic-04.jpg';
export { default as clinic_11} from '../../public/client/assets/images/clinic/clinic-11.jpg';
export { default as clinic_12} from '../../public/client/assets/images/clinic/clinic-12.jpg';
export { default as clinic_13} from '../../public/client/assets/images/clinic/clinic-13.jpg';
export { default as clinic_14} from '../../public/client/assets/images/clinic/clinic-14.jpg';
export { default as clinic_15} from '../../public/client/assets/images/clinic/clinic-15.jpg';
export { default as clinic_16} from '../../public/client/assets/images/clinic/clinic-16.jpg';
export { default as clinic_17} from '../../public/client/assets/images/clinic/clinic-17.jpg';
export { default as clinic_18} from '../../public/client/assets/images/clinic/clinic-18.jpg';
export { default as clinic_1} from '../../public/client/assets/images/clinic/clinic-icon1.png';
export { default as clinic_2} from '../../public/client/assets/images/clinic/clinic-icon2.png';
export { default as clinic_3} from '../../public/client/assets/images/clinic/clinic-icon3.png';
export { default as clinic_4} from '../../public/client/assets/images/clinic/clinic-icon4.png';
export { default as clinic_5} from '../../public/client/assets/images/clinic/clinic-icon5.png';
export { default as clinic_6} from '../../public/client/assets/images/clinic/clinic-icon6.png';
export { default as doctor_img2} from '../../public/client/assets/images/doctors/doctor-img2.png';
export { default as background} from '../../public/client/assets/images/banner-6.jpg';
export {default as book_doc_05} from '../../public/client/assets/images/doctors/book-doc-05.jpg';
export {default as book_doc_04} from '../../public/client/assets/images/doctors/book-doc-04.jpg';
export {default as book_doc_03} from '../../public/client/assets/images/doctors/book-doc-03.jpg';
export {default as book_doc_02} from '../../public/client/assets/images/doctors/book-doc-02.jpg';



export {default as IMG01}  from "../../public/client/assets/images/doctors/doctor-thumb-02.jpg";
export {default as spec1 }  from "../../public/client/assets/images/shapes/spec-01.png";
export {default as spec2 }  from "../../public/client/assets/images/shapes/spec-02.png";
export {default as spec3 } from "../../public/client/assets/images/shapes/spec-03.png";
export {default as spec4}  from "../../public/client/assets/images/shapes/spec-04.png";
export {default as spec5 }  from "../../public/client/assets/images/shapes/spec-05.png";
export {default as spec6 }  from "../../public/client/assets/images/shapes/spec-06.png";
export {default as spec7 }  from "../../public/client/assets/images/shapes/spec-07.png";
export {default as bro1 }  from "../../public/client/assets/images/shapes/bro-01.png";
export {default as bro2 }  from "../../public/client/assets/images/shapes/bro-02.png";
export {default as bro3 }  from "../../public/client/assets/images/shapes/bro-03.png";
export {default as  bro4}  from "../../public/client/assets/images/shapes/bro-04.png";
export {default as bro5 }  from "../../public/client/assets/images/shapes/bro-05.png";
export {default as mapplus}  from "../../public/client/assets/images/shapes/map-plus.png";
export {default as alarm}  from "../../public/client/assets/images/shapes/alarm.png";
export {default as exper}  from "../../public/client/assets/images/shapes/exper.png";
export {default as consult}  from "../../public/client/assets/images/shapes/consult.png";
export {default as Doctor1}  from "../../public/client/assets/images/doctors/doctor-01.jpg";
export {default as Doctor2}  from "../../public/client/assets/images/doctors/doctor-02.jpg";
export {default as Doctor3 }  from "../../public/client/assets/images/doctors/doctor-03.jpg";
export {default as Doctor4 } from "../../public/client/assets/images/doctors/doctor-04.jpg";
export {default as Doctor5 } from "../../public/client/assets/images/doctors/doctor-05.jpg";
export {default as Shape1 }  from "../../public/client/assets/images/shapes/blog-img01.jpg";
export {default as Shape2 }from "../../public/client/assets/images/shapes/blog-img02.jpg";
export {default as Shape3 } from "../../public/client/assets/images/shapes/blog-img03.jpg";
export {default as FooterLogo}from "../../public/client/assets/images/footer-logo.png"
export {default as spec }from "../../public/client/assets/images/shapes/spec.png"

export {default as  operationimg} from "../../public/client/assets/images/shapes/blog-img01.png";
export {default as  clinicbg} from"../../public/client/assets/images/shapes/clinic-bg.png";
export {default as  clinichover1} from "../../public/client/assets/images/icons/clinic-hover-01.png";
export {default as  clinichover4} from "../../public/client/assets/images/icons/clinic-hover-04.png";
export {default as  clinichover6} from "../../public/client/assets/images/icons/clinic-hover-06.png";
export {default as  cardiology} from "../../public/client/assets/images/icons/cardiology.png";
export {default as  BannerImg} from "../../public/client/assets/images/doctor-banner1.png";
export {default as  Visit1} from "../../public/client/assets/images/icons/visit-01.png";
export {default as  Visit2} from "../../public/client/assets/images/icons/visit-02.png";
export {default as  Visit3} from "../../public/client/assets/images/icons/visit-03.png";
export {default as  blogwrap1} from "../../public/client/assets/images/blog/blog-wrap-01.jpg";
export {default as  blogwrap2} from "../../public/client/assets/images/blog/blog-wrap-02.jpg";
export {default as  blogwrap3} from "../../public/client/assets/images/blog/blog-wrap-03.jpg";
export {default as  blogwrap4} from "../../public/client/assets/images/blog/blog-wrap-04.jpg";
